server:
  port: 8082
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 

spring:
  application:
    name: api-gateway-service
    
  cloud:
    gateway:
      routes:
      - id: patient-service
        uri: lb://patient-service
        predicates:
        - Path=/api/patient/**
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/api/user/**
